#!/usr/bin/env python3
"""Set up the nnU-Net v2 environment for ToothFairy3.

Creates directory structure, symlinks the read-only dataset, sets environment
variables, verifies nnU-Net CLI availability, and writes a sourceable shell
snippet to ``outputs/nnunet_env.sh``.

Usage
-----
    python scripts/02_setup_nnunet.py --config configs/pipeline_config.yaml
"""

from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Ensure the project package is importable when running from the repo root.
# ---------------------------------------------------------------------------
_SCRIPT_DIR = Path(__file__).resolve().parent
_PROJECT_ROOT = _SCRIPT_DIR.parent
sys.path.insert(0, str(_PROJECT_ROOT / "src"))

from dental_pipeline.config import load_config  # noqa: E402
from dental_pipeline.nnunet_setup import NNUNetSetup  # noqa: E402


def _setup_logging(log_dir: Path) -> None:
    """Configure root logger to write to both console and a log file."""
    log_dir.mkdir(parents=True, exist_ok=True)
    log_file = log_dir / "02_setup_nnunet.log"

    handlers: list[logging.Handler] = [
        logging.StreamHandler(sys.stdout),
        logging.FileHandler(str(log_file), mode="a", encoding="utf-8"),
    ]

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s | %(levelname)-8s | %(name)s | %(message)s",
        handlers=handlers,
    )


def _write_env_script(env_vars: dict[str, str], output_dir: Path) -> Path:
    """Write a shell snippet that can be sourced to set nnU-Net env vars.

    Parameters
    ----------
    env_vars : dict[str, str]
        Environment variable name → value mapping.
    output_dir : Path
        Directory in which to write ``nnunet_env.sh``.

    Returns
    -------
    Path
        Absolute path to the generated script.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    script_path = output_dir / "nnunet_env.sh"

    lines = [
        "#!/usr/bin/env bash",
        "# nnU-Net v2 environment variables – auto-generated by 02_setup_nnunet.py",
        "# Source this file before running nnU-Net commands:",
        "#   source outputs/nnunet_env.sh",
        "",
    ]
    for key, value in env_vars.items():
        lines.append(f'export {key}="{value}"')
    lines.append("")  # trailing newline

    script_path.write_text("\n".join(lines), encoding="utf-8")
    return script_path


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Set up nnU-Net v2 environment for ToothFairy3 dental CBCT segmentation.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--config",
        type=str,
        required=True,
        help="Path to the YAML pipeline configuration file (e.g. configs/pipeline_config.yaml).",
    )
    return parser.parse_args()


def main() -> int:
    """Entry-point for the nnU-Net setup script.

    Returns
    -------
    int
        0 on success, 1 on failure.
    """
    args = _parse_args()
    config = load_config(args.config)

    _setup_logging(Path(config.paths.logs))
    logger = logging.getLogger(__name__)

    try:
        setup = NNUNetSetup(config)
        setup.run()

        # Print the environment variables so the user can set them manually
        # (useful for interactive sessions or non-Python workflows).
        env_vars = setup.get_env_vars()

        logger.info("")
        logger.info("=" * 60)
        logger.info("nnU-Net environment variables (set these in your shell):")
        logger.info("=" * 60)
        for key, value in env_vars.items():
            logger.info("  export %s=\"%s\"", key, value)

        # Write sourceable shell snippet.
        output_dir = Path(config.paths.output_root)
        script_path = _write_env_script(env_vars, output_dir)
        logger.info("")
        logger.info(
            "Shell snippet written to: %s", script_path.resolve()
        )
        logger.info("  → source %s", script_path)
        logger.info("")

        logger.info("nnU-Net setup complete (labels remapped to consecutive IDs). You can now run preprocessing.")
        return 0

    except FileNotFoundError as exc:
        logger.error("Dataset not found: %s", exc)
        return 1
    except RuntimeError as exc:
        logger.error("Setup verification failed: %s", exc)
        return 1
    except Exception as exc:
        logger.exception("Unexpected error during nnU-Net setup: %s", exc)
        return 1


if __name__ == "__main__":
    sys.exit(main())
