#!/usr/bin/env bash
# nnU-Net v2 environment variables – auto-generated by 02_setup_nnunet.py
# Source this file before running nnU-Net commands:
#   source outputs/nnunet_env.sh

export nnUNet_raw="/usershome/cs671_user15/Dobbe AI/dental-segmentation/outputs/nnunet_raw"
export nnUNet_preprocessed="/usershome/cs671_user15/Dobbe AI/dental-segmentation/outputs/nnunet_preprocessed"
export nnUNet_results="/usershome/cs671_user15/Dobbe AI/dental-segmentation/outputs/nnunet_results"
